"""The conversation-title attachment is a serialization boundary for LLM output.

``_ChatSlot.display_title`` is generated by a model
(``chat_title._generate_title_via_kiro``), and the slot's own serialization runs
two scanners over it before the dashboard sees it. ``/api/telemetry/startup`` is
a SECOND boundary for the same field, so it must run them too — the scan is
load-bearing rather than duplicated, because a title set through
``api_chat_slot_resume`` is written to the slot unredacted and nothing upstream
of this handler has sanitised it. A title read back from a transcript takes the
same path, so where a title came from cannot change what leaves here.

The second invariant here is cache purity: ``cost_breakdown`` returns its
memoised object by reference, so attaching a title in place would write into
module-global state and keep serving that title for the rest of the TTL after the
conversation was renamed or closed.
The third invariant is that the stand-in below mirrors the REAL accessor. The slot
map is private (``DashboardState._slots``); ``get_slot()`` is the only public way
in. A double that instead exposes a ``slots`` attribute passes while production
resolves nothing and every row renders unnamed, so one test here asserts the
production class actually carries the accessor this handler calls.

The fourth is what counts as a title on the persisted path. ``get_metadata``
reports only an explicit ``metadata["title"]``; ``list_sessions`` would fall back
to the first user message and then to the session key, which turns a ranking
label into prompt text and removes any way to tell a named conversation from an
unnamed one. The tests below pin that only an explicit title is read.
"""
import json
from types import SimpleNamespace

import pytest

from kiro_crew.dashboard.chat_utils import slot_transcript_key
from kiro_crew.dashboard.handlers.telemetry import _with_conversation_titles
from kiro_crew.dashboard.state import NEW_SESSION_TITLE, DashboardState
from kiro_crew.history import ConversationLog


def _request(slots: dict, conversation_log=None) -> SimpleNamespace:
    """Minimal stand-in for the aiohttp request the handler reads.

    Exposes ``get_slot`` and ``conversation_log`` and nothing else, matching
    ``DashboardState``'s public surface -- a double with a richer interface than
    production can hide exactly the defect this file exists to catch.
    """
    state = SimpleNamespace(
        get_slot=lambda key: slots.get(key),
        conversation_log=conversation_log,
    )
    return SimpleNamespace(app={"state": state})


def test_the_handler_calls_an_accessor_the_real_state_actually_has():
    # Pins the double to production: renaming or dropping get_slot must fail here
    # rather than silently degrade every row to "Untitled" at runtime.
    assert callable(getattr(DashboardState, "get_slot", None))
    assert not hasattr(DashboardState, "slots")
    # Same for the transcript store the closed-conversation fallback reads.
    assert "conversation_log" in DashboardState.__init__.__code__.co_names or hasattr(
        DashboardState, "conversation_log"
    )


def _cost(*slot_keys: str) -> dict:
    return {"conversations": [{"slot": k, "credits": 1.0} for k in slot_keys]}


@pytest.mark.asyncio
async def test_a_credential_shaped_title_is_redacted():
    # A real AWS-key shape. The scanner recognises it; the point is that this
    # endpoint runs the scanner at all.
    leaked = "notes for AKIA" + "IOSFODNN7EXAMPLE"
    slots = {"chat-1-1": SimpleNamespace(display_title=leaked)}
    out = await _with_conversation_titles(_request(slots), _cost("chat-1-1"))
    title = out["conversations"][0]["title"]
    assert "AKIA" + "IOSFODNN7EXAMPLE" not in title
    assert "REDACTED" in title


@pytest.mark.asyncio
async def test_an_ordinary_title_survives_unchanged():
    slots = {"chat-1-1": SimpleNamespace(display_title="Telemetry cost page")}
    out = await _with_conversation_titles(_request(slots), _cost("chat-1-1"))
    assert out["conversations"][0]["title"] == "Telemetry cost page"


@pytest.mark.asyncio
async def test_the_input_payload_is_not_mutated():
    # cost_breakdown hands back its cache by reference; writing through it would
    # pin this title into module-global state for the rest of the TTL.
    payload = _cost("chat-1-1")
    slots = {"chat-1-1": SimpleNamespace(display_title="Telemetry cost page")}
    out = await _with_conversation_titles(_request(slots), payload)
    assert "title" not in payload["conversations"][0]
    assert out["conversations"][0]["title"] == "Telemetry cost page"
    assert out["conversations"][0] is not payload["conversations"][0]


@pytest.mark.asyncio
async def test_a_conversation_with_no_slot_and_no_transcript_gets_no_title():
    out = await _with_conversation_titles(_request({}), _cost("chat-9-9"))
    assert "title" not in out["conversations"][0]


@pytest.mark.asyncio
async def test_the_placeholder_title_is_treated_as_absent():
    slots = {"chat-1-1": SimpleNamespace(display_title=NEW_SESSION_TITLE)}
    out = await _with_conversation_titles(_request(slots), _cost("chat-1-1"))
    assert "title" not in out["conversations"][0]


@pytest.mark.asyncio
async def test_a_state_without_the_accessor_returns_the_payload_unchanged():
    req = SimpleNamespace(app={"state": SimpleNamespace()})
    payload = _cost("chat-1-1")
    out = await _with_conversation_titles(req, payload)
    # Content, not identity: the handler always rebuilds the rows so it can
    # never write into the caller's (cached) object.
    assert out == payload
    assert "title" not in out["conversations"][0]


class TestClosedConversations:
    """A conversation with no live slot is named from its transcript metadata.

    The write side already persists it (``chat_title._persist_title`` ->
    ``ConversationLog.set_title``). These drive the REAL ``ConversationLog`` so
    the slot-key-to-transcript-key mapping is production's, not a restatement of
    it -- that mapping is where a naive ``dashboard_`` + slot goes wrong for every
    channel-born conversation.
    """

    @pytest.mark.asyncio
    async def test_a_persisted_title_names_a_closed_conversation(self, tmp_path):
        log = ConversationLog(tmp_path)
        log.set_title(slot_transcript_key("chat-1-1"), "Telemetry cost page")

        out = await _with_conversation_titles(
            _request({}, conversation_log=log), _cost("chat-1-1")
        )
        assert out["conversations"][0]["title"] == "Telemetry cost page"

    @pytest.mark.asyncio
    async def test_a_channel_conversation_resolves_through_the_real_mapping(self, tmp_path):
        # The shape a naive f"dashboard_{slot}" join silently misses.
        slot_key = "slack_1785370133.085469"
        log = ConversationLog(tmp_path)
        log.set_title(slot_transcript_key(slot_key), "Support thread")

        out = await _with_conversation_titles(
            _request({}, conversation_log=log), _cost(slot_key)
        )
        assert out["conversations"][0]["title"] == "Support thread"

    @pytest.mark.asyncio
    async def test_the_live_title_wins_over_the_persisted_one(self, tmp_path):
        # A rename lands on the slot first and is flushed to the transcript on a
        # worker thread, so the live value is the fresher of the two.
        log = ConversationLog(tmp_path)
        log.set_title(slot_transcript_key("chat-1-1"), "Old name")
        slots = {"chat-1-1": SimpleNamespace(display_title="New name")}

        out = await _with_conversation_titles(
            _request(slots, conversation_log=log), _cost("chat-1-1")
        )
        assert out["conversations"][0]["title"] == "New name"

    @pytest.mark.asyncio
    async def test_a_transcript_without_an_explicit_title_yields_none(self, tmp_path):
        # The `list_sessions` contract would answer with the first user message
        # and then with the session key, so this row would render as prompt text
        # or as `dashboard_chat-1-1`. Only an explicit metadata title counts.
        path = tmp_path / "dashboard_chat-1-1.jsonl"
        path.write_text(
            json.dumps({"_type": "metadata", "created_at": "2026-08-01T00:00:00+00:00"})
            + "\n"
            + json.dumps({"role": "user", "content": "please audit the billing export"})
            + "\n",
            encoding="utf-8",
        )
        log = ConversationLog(tmp_path)

        out = await _with_conversation_titles(
            _request({}, conversation_log=log), _cost("chat-1-1")
        )
        row = out["conversations"][0]
        assert "title" not in row, f"unnamed row acquired a title: {row.get('title')!r}"

    @pytest.mark.asyncio
    async def test_a_persisted_title_is_redacted_like_a_live_one(self, tmp_path):
        leaked = "notes for AKIA" + "IOSFODNN7EXAMPLE"
        log = ConversationLog(tmp_path)
        log.set_title(slot_transcript_key("chat-1-1"), leaked)

        out = await _with_conversation_titles(
            _request({}, conversation_log=log), _cost("chat-1-1")
        )
        title = out["conversations"][0]["title"]
        assert "AKIA" + "IOSFODNN7EXAMPLE" not in title
        assert "REDACTED" in title

    @pytest.mark.asyncio
    async def test_rows_sharing_one_transcript_are_read_once(self, tmp_path):
        log = ConversationLog(tmp_path)
        log.set_title(slot_transcript_key("chat-1-1"), "Telemetry cost page")
        reads: list[str] = []
        real = log.get_metadata

        def counting(key: str):
            reads.append(key)
            return real(key)

        log.get_metadata = counting  # type: ignore[method-assign]
        payload = _cost("chat-1-1", "chat-1-1", "chat-1-1")

        out = await _with_conversation_titles(_request({}, conversation_log=log), payload)
        assert [r["title"] for r in out["conversations"]] == ["Telemetry cost page"] * 3
        assert len(reads) == 1, f"one transcript read {len(reads)} times: {reads}"
