/**
 * Supported UI languages — the single source of truth.
 *
 * Adding a language is a DATA change, not a code change — exactly three edits:
 *   1. add `src/i18n/locales/<code>.json` (same key set as `en.json`)
 *   2. add one entry here
 *   3. register the catalog in `src/i18n/index.ts` `CATALOGS`
 *
 * No component changes, and no test changes: `catalogParity.test.ts` derives its
 * cases from this list and reads catalogs from the runtime `CATALOGS` map, so a
 * new language automatically gains its own parity/placeholder/empty-value tests.
 * A half-added language therefore fails CI (naming the missing piece) instead of
 * silently rendering English.
 *
 * `label` is deliberately the language's own endonym (自称) — a user looking
 * for Chinese scans for "简体中文", not "Chinese (Simplified)". Endonyms are
 * NOT translated (they read the same in every UI language), which is why they
 * live here as plain strings rather than in the catalogs.
 */

export interface LanguageEntry {
  /** BCP-47 tag. Must match the catalog filename and the i18next resource key. */
  code: string
  /** Endonym shown in the picker — never translated. */
  label: string
  /**
   * Hide from the picker in a production build.
   *
   * Only the pseudolocale sets this. It has to be a REGISTERED language —
   * `resolveLanguage()` matches on the primary subtag, so an unregistered `en-XA`
   * silently collapses to `en` and the pseudolocale never activates — but a user must
   * not be able to select an accented UI in a shipped build. Registration and
   * visibility are separate concerns, so they are separate fields.
   */
  devOnly?: boolean
}

/**
 * Ordered by global speaker count, so the picker's top entries are the ones
 * most users are looking for rather than an alphabetical accident.
 *
 * Right-to-left languages (Arabic, Urdu) are deliberately absent: the catalogs
 * would translate correctly, but the dashboard's layout is built from
 * physical-direction Tailwind utilities (`pl-*`, `left-*`, `text-left`) and
 * unmirrored directional icons, so an RTL locale would render readable text in
 * a visibly wrong shell. RTL needs `dir="rtl"` plus a logical-property
 * conversion first; shipping the catalog before that would be a worse
 * experience than English.
 */
export const SUPPORTED_LANGUAGES: readonly LanguageEntry[] = [
  { code: 'en', label: 'English' },
  { code: 'zh-CN', label: '简体中文' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'es', label: 'Español' },
  { code: 'fr', label: 'Français' },
  { code: 'bn', label: 'বাংলা' },
  { code: 'pt', label: 'Português' },
  { code: 'ru', label: 'Русский' },
  { code: 'de', label: 'Deutsch' },
  { code: 'ja', label: '日本語' },
  { code: 'ko', label: '한국어' },
  { code: 'it', label: 'Italiano' },
  /**
   * Pseudolocale, not a language. Every string is accented, padded to the IBM/W3C
   * expansion budget and bracketed, so in an `en-XA` build any plain-Latin text on
   * screen is untranslated BY CONSTRUCTION — no heuristic, no scanner, no allowlist.
   * The brackets also make a sentence split across two keys visible as `[…] […]`.
   *
   * `en-XA` is the ICU/Android private-use convention. Windows once used a real locale
   * tag for this and broke its own CI, which is why it must come from the private-use
   * range rather than being an invented code.
   *
   * Generated by `scripts/gen-pseudolocale.mjs`; `--check` fails CI when it drifts from
   * `en.json`, because a stale pseudolocale silently stops detecting.
   */
  { code: 'en-XA', label: '[Pseudolocale]', devOnly: true },
] as const

/** The fallback language. Its catalog is the key-set authority for all others. */
export const DEFAULT_LANGUAGE = 'en'

/**
 * Sentinel for "follow the browser" — persisted as the empty string so an
 * unset config field (the dataclass default) already means auto-detect, with
 * no migration needed for existing installs.
 */
export const AUTO_LANGUAGE = ''

export const SUPPORTED_CODES: readonly string[] = SUPPORTED_LANGUAGES.map(l => l.code)

/**
 * Codes a BROWSER tag may resolve to.
 *
 * Three lists, three questions, and conflating them is a real bug: registering the
 * pseudolocale made `en` ambiguous for `matchConfident()`, so `en-GB` stopped resolving
 * confidently to `en`. A browser never sends `en-XA`, so it has no business in
 * detection.
 *
 *   `SUPPORTED_CODES`      — what the runtime can resolve when asked explicitly
 *   `DETECTABLE_CODES`     — what a browser `Accept-Language` tag may resolve to
 *   `PICKABLE_LANGUAGES`   — what a user may choose in the UI
 *   `isRestorableLanguage` — what a PERSISTED choice may resolve to in this build
 */
export const DETECTABLE_CODES: readonly string[] = SUPPORTED_LANGUAGES
  .filter(l => !l.devOnly)
  .map(l => l.code)

/**
 * The languages a user can actually pick. Everything registered, minus the dev-only
 * pseudolocale, in a production build.
 *
 * Read this in UI; read `SUPPORTED_LANGUAGES` when you mean "what can the runtime
 * resolve" (catalog registration, parity tests, `resolveLanguage`).
 */
export const PICKABLE_LANGUAGES: readonly LanguageEntry[] = SUPPORTED_LANGUAGES.filter(
  l => !l.devOnly || import.meta.env.DEV,
)

const DEV_ONLY_CODES: readonly string[] = SUPPORTED_LANGUAGES
  .filter(l => l.devOnly)
  .map(l => l.code)

export function isSupportedLanguage(code: string): boolean {
  return SUPPORTED_CODES.includes(code)
}

export function isDevOnlyLanguage(code: string): boolean {
  return DEV_ONLY_CODES.includes(code)
}

/**
 * May this code be RESTORED from persisted state (config / localStorage)?
 *
 * Hiding the pseudolocale from the picker is not enough on its own: a dev who selects
 * `en-XA` writes it to `dashboard.language`, and any production build reading that
 * config — a shared gateway config, a copied install, the same machine after a
 * `npm run build` — resolved it happily, because `isSupportedLanguage` only asks
 * "is it registered". The result is an accented, padded UI with no picker entry
 * explaining it and `SimpleSelect` showing the raw `en-XA` code in its trigger.
 *
 * Persisted state is therefore its OWN question, alongside the three lists above:
 * a dev-only code stays resolvable when asked explicitly (`resolveLanguage('en-XA')`
 * in a dev build, the parity tests) but a stored one degrades to auto-detect in a
 * shipped build, completing the "resolvable but not selectable" invariant.
 */
export function isRestorableLanguage(code: string): boolean {
  if (!isSupportedLanguage(code)) return false
  return import.meta.env.DEV || !isDevOnlyLanguage(code)
}

/** Endonym for a code, or the raw code when it isn't one we ship. */
export function languageLabel(code: string): string {
  return SUPPORTED_LANGUAGES.find(l => l.code === code)?.label ?? code
}
